// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Henrik O. Sørensen
// This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of
// the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;

namespace libbgcode.NET;

/// <summary>
/// Converts whole files between the ASCII G-code PrusaSlicer writes and the binary container.
/// </summary>
/// <remarks>
/// <para>
/// <b>The ASCII conventions are PrusaSlicer's, learned from its output, not from the reference
/// converter's code.</b> A producer line (<c>; generated by … on …</c>), a head of
/// <c>; key = value</c> comments a printer reads from the first kilobytes, thumbnail sections
/// (<c>; thumbnail begin WxH N</c> … <c>; thumbnail end</c>, <c>_QOI</c> and <c>_JPG</c>
/// variants, base64 in comment lines), print statistics after the G-code, and the config section
/// (<c>; prusaslicer_config = begin</c> … <c>end</c>) - joined since PrusaSlicer 3 by a JSON one
/// (<c>; prusaslicer_json_config</c>). Which keys the printer and print blocks gather is
/// <see cref="AsciiMetadataKeys"/>'s observation.
/// </para>
/// <para>
/// <b>Validity, not byte-identity, is the goal.</b> Files this writes are verified by the
/// reference implementation and read back by <see cref="BgcodeReader"/>; the reference converter
/// may lay bytes out differently. The G-code itself passes through the encoding's reconstruction,
/// so a converted-back file carries equivalent G-code, not the original bytes.
/// </para>
/// <para>
/// <b>Both directions read their whole input first.</b> The binary container wants the metadata
/// that ASCII files put at the end before any G-code, and the ASCII layout wants the print
/// statistics that live in a block after the G-code. Memory is the input's size.
/// </para>
/// </remarks>
public static class BgcodeConverter
{
    private const string ConfigBegin = "; prusaslicer_config = begin";

    private const string ConfigEnd = "; prusaslicer_config = end";

    private const string JsonConfigBegin = "; prusaslicer_json_config = begin";

    private const string JsonConfigEnd = "; prusaslicer_json_config = end";

    private const string GeneratedBy = "; generated by ";

    private const int Base64LineWidth = 64;

    /// <summary>
    /// Converts binary G-code to ASCII G-code in PrusaSlicer's layout.
    /// </summary>
    /// <param name="binary">The binary file. Seekable; read entirely.</param>
    /// <param name="ascii">Where the ASCII text goes. Lines end in <c>\n</c>.</param>
    /// <param name="options">Reader bounds and verification; verification is on by default here.</param>
    /// <exception cref="InvalidDataException">The input is not readable binary G-code.</exception>
    public static void ToAscii(Stream binary, TextWriter ascii, BgcodeReaderOptions? options = null)
    {
        ArgumentNullException.ThrowIfNull(binary);
        ArgumentNullException.ThrowIfNull(ascii);

        BgcodeReader reader = BgcodeReader.Open(binary, options ?? new BgcodeReaderOptions { VerifyChecksum = true })
                              ?? throw new InvalidDataException("Not a readable binary G-code file: the header is missing or unknown.");

        string? fileMetadata = null;
        string? printerMetadata = null;
        string? printMetadata = null;
        string? slicerIni = null;
        string? slicerJson = null;
        List<(BgcodeThumbnailParameters parameters, byte[] image)> thumbnails = [];
        StringBuilder gcode = new();
        int index = 0;

        while (reader.NextBlock() is { } block)
        {
            index++;

            if (block.Type == BgcodeBlockType.Thumbnail)
            {
                byte[] image = reader.ReadData(block)
                               ?? throw new InvalidDataException($"Block {index} ({block.Type}) could not be read.");

                thumbnails.Add((block.Thumbnail!.Value, image));

                continue;
            }

            string text = reader.ReadText(block)
                          ?? throw new InvalidDataException($"Block {index} ({block.Type}) could not be read.");

            switch (block.Type)
            {
                case BgcodeBlockType.FileMetadata:
                    fileMetadata = text;

                    break;

                case BgcodeBlockType.PrinterMetadata:
                    printerMetadata = text;

                    break;

                case BgcodeBlockType.PrintMetadata:
                    printMetadata = text;

                    break;

                case BgcodeBlockType.SlicerMetadata:
                    if (block.MetadataEncoding == BgcodeMetadataEncoding.Json)
                    {
                        slicerJson = text;
                    }
                    else
                    {
                        slicerIni = text;
                    }

                    break;

                default:
                    gcode.Append(text);

                    break;
            }
        }

        if (!reader.AtEnd)
        {
            throw new InvalidDataException($"The file is malformed after block {index}.");
        }

        WriteProducerLine(ascii, fileMetadata);
        WriteMetadataComments(ascii, printerMetadata);

        foreach ((BgcodeThumbnailParameters parameters, byte[] image) in thumbnails)
        {
            WriteThumbnailSection(ascii, parameters, image);
        }

        ascii.Write('\n');
        ascii.Write(gcode.ToString());
        ascii.Write('\n');
        WriteMetadataComments(ascii, printMetadata);
        ascii.Write('\n');

        if (slicerJson is not null)
        {
            ascii.Write(JsonConfigBegin);
            ascii.Write('\n');

            foreach (ReadOnlySpan<char> line in slicerJson.AsSpan().EnumerateLines())
            {
                if (line.Length > 0)
                {
                    ascii.Write("; ");
                    ascii.Write(line);
                    ascii.Write('\n');
                }
            }

            ascii.Write(JsonConfigEnd);
            ascii.Write("\n\n");
        }

        ascii.Write(ConfigBegin);
        ascii.Write('\n');
        WriteMetadataComments(ascii, slicerIni);
        ascii.Write(ConfigEnd);
        ascii.Write('\n');
        ascii.Flush();
    }

    /// <summary>
    /// Converts ASCII G-code in PrusaSlicer's layout to the binary container.
    /// </summary>
    /// <param name="ascii">The ASCII text; read entirely.</param>
    /// <param name="binary">Where the binary file goes.</param>
    /// <param name="options">Compression, encoding and checksum choices; PrusaSlicer's when omitted.</param>
    /// <remarks>
    /// Any text converts. A file without a config section gets an empty slicer metadata block,
    /// and one without recognisable head comments an empty printer metadata block - the container
    /// requires both, and a printer decides for itself what it makes of an empty one.
    /// </remarks>
    public static void ToBinary(TextReader ascii, Stream binary, BgcodeConverterOptions? options = null)
    {
        ArgumentNullException.ThrowIfNull(ascii);
        ArgumentNullException.ThrowIfNull(binary);

        options ??= BgcodeConverterOptions.Default;

        AsciiParse parsed = Parse(ascii);

        using BgcodeWriter writer = new(binary, options.ChecksumType, leaveOpen: true);

        if (parsed.Producer is not null)
        {
            string fileMetadata = "Producer=" + parsed.Producer + "\n"
                                  + (parsed.ProducedOn is null ? string.Empty : "Produced on=" + parsed.ProducedOn + "\n");

            writer.WriteFileMetadata(fileMetadata, options.FileMetadataCompression);
        }

        writer.WritePrinterMetadata(AsciiMetadataKeys.BlockText(AsciiMetadataKeys.Printer, parsed.Captured), options.PrinterMetadataCompression);

        foreach ((BgcodeThumbnailParameters parameters, byte[] image) in parsed.Thumbnails)
        {
            writer.WriteThumbnail(parameters, image, options.ThumbnailCompression);
        }

        writer.WritePrintMetadata(AsciiMetadataKeys.BlockText(AsciiMetadataKeys.Print, parsed.Captured), options.PrintMetadataCompression);
        writer.WriteSlicerMetadata(parsed.SlicerIni.ToString(), BgcodeMetadataEncoding.Ini, options.SlicerMetadataCompression);

        if (parsed.SlicerJson is not null)
        {
            writer.WriteSlicerMetadata(parsed.SlicerJson.ToString(), BgcodeMetadataEncoding.Json, options.SlicerMetadataCompression);
        }

        writer.WriteGCode(parsed.GCode.ToString(), options.GCodeEncoding, options.GCodeCompression);
    }

    private static AsciiParse Parse(TextReader ascii)
    {
        AsciiParse parsed = new();
        Section section = Section.None;
        StringBuilder base64 = new();
        BgcodeThumbnailParameters thumbnail = default;

        while (ascii.ReadLine() is { } rawLine)
        {
            string line = rawLine.TrimEnd('\r');

            switch (section)
            {
                case Section.Thumbnail:
                    if (IsThumbnailEnd(line))
                    {
                        parsed.Thumbnails.Add((thumbnail, Convert.FromBase64String(base64.ToString())));
                        base64.Clear();
                        section = Section.None;
                    }
                    else
                    {
                        base64.Append(StripComment(line));
                    }

                    continue;

                case Section.Config:
                    if (line == ConfigEnd)
                    {
                        section = Section.None;
                    }
                    else if (TrySplitComment(line, out string key, out string value))
                    {
                        parsed.SlicerIni.Append(key).Append('=').Append(value).Append('\n');
                    }

                    continue;

                case Section.JsonConfig:
                    if (line == JsonConfigEnd)
                    {
                        section = Section.None;
                    }
                    else
                    {
                        parsed.SlicerJson ??= new StringBuilder();
                        parsed.SlicerJson.Append(StripComment(line)).Append('\n');
                    }

                    continue;
            }

            if (parsed.Producer is null && line.StartsWith(GeneratedBy, StringComparison.Ordinal))
            {
                string rest = line[GeneratedBy.Length..];
                int on = rest.IndexOf(" on ", StringComparison.Ordinal);

                parsed.Producer = on < 0 ? rest : rest[..on];
                parsed.ProducedOn = on < 0 ? null : rest[(on + 4)..];

                continue;
            }

            if (line == ConfigBegin)
            {
                section = Section.Config;

                continue;
            }

            if (line == JsonConfigBegin)
            {
                section = Section.JsonConfig;
                parsed.SlicerJson ??= new StringBuilder();

                continue;
            }

            if (TryParseThumbnailBegin(line, out thumbnail))
            {
                section = Section.Thumbnail;

                continue;
            }

            if (TrySplitComment(line, out string metadataKey, out string metadataValue) && AsciiMetadataKeys.All.Contains(metadataKey))
            {
                parsed.Captured.TryAdd(metadataKey, metadataValue);

                continue;
            }

            parsed.GCode.Append(line).Append('\n');
        }

        return parsed;
    }

    private static void WriteProducerLine(TextWriter ascii, string? fileMetadata)
    {
        string? producer = null;
        string? producedOn = null;

        if (fileMetadata is not null)
        {
            foreach (ReadOnlySpan<char> line in fileMetadata.AsSpan().EnumerateLines())
            {
                int equals = line.IndexOf('=');

                if (equals < 0)
                {
                    continue;
                }

                if (line[..equals].SequenceEqual("Producer"))
                {
                    producer = line[(equals + 1)..].ToString();
                }
                else if (line[..equals].SequenceEqual("Produced on"))
                {
                    producedOn = line[(equals + 1)..].ToString();
                }
            }
        }

        if (producer is null)
        {
            return;
        }

        ascii.Write(GeneratedBy);
        ascii.Write(producer);

        if (producedOn is not null)
        {
            ascii.Write(" on ");
            ascii.Write(producedOn);
        }

        ascii.Write("\n\n\n");
    }

    /// <summary>Each <c>key=value</c> line of a metadata block as a <c>; key = value</c> comment.</summary>
    private static void WriteMetadataComments(TextWriter ascii, string? metadata)
    {
        if (metadata is null)
        {
            return;
        }

        foreach (ReadOnlySpan<char> line in metadata.AsSpan().EnumerateLines())
        {
            if (line.Length == 0)
            {
                continue;
            }

            int equals = line.IndexOf('=');

            ascii.Write("; ");

            if (equals < 0)
            {
                ascii.Write(line);
            }
            else
            {
                ascii.Write(line[..equals]);
                ascii.Write(" = ");
                ascii.Write(line[(equals + 1)..]);
            }

            ascii.Write('\n');
        }
    }

    private static void WriteThumbnailSection(TextWriter ascii, BgcodeThumbnailParameters parameters, byte[] image)
    {
        string tag = parameters.Format switch
        {
            BgcodeThumbnailFormat.Jpg => "thumbnail_JPG",
            BgcodeThumbnailFormat.Qoi => "thumbnail_QOI",
            _ => "thumbnail",
        };
        string encoded = Convert.ToBase64String(image);

        ascii.Write("\n;\n; ");
        ascii.Write(tag);
        ascii.Write(" begin ");
        ascii.Write(parameters.Width.ToString(CultureInfo.InvariantCulture));
        ascii.Write('x');
        ascii.Write(parameters.Height.ToString(CultureInfo.InvariantCulture));
        ascii.Write(' ');
        ascii.Write(encoded.Length.ToString(CultureInfo.InvariantCulture));
        ascii.Write('\n');

        for (int i = 0; i < encoded.Length; i += Base64LineWidth)
        {
            ascii.Write("; ");
            ascii.Write(encoded.AsSpan(i, Math.Min(Base64LineWidth, encoded.Length - i)));
            ascii.Write('\n');
        }

        ascii.Write("; ");
        ascii.Write(tag);
        ascii.Write(" end\n;\n");
    }

    /// <summary><c>; thumbnail begin WxH N</c>, with the <c>_JPG</c> and <c>_QOI</c> tag variants.</summary>
    private static bool TryParseThumbnailBegin(string line, out BgcodeThumbnailParameters parameters)
    {
        parameters = default;

        if (!line.StartsWith("; thumbnail", StringComparison.Ordinal))
        {
            return false;
        }

        string[] words = line[2..].Split(' ', StringSplitOptions.RemoveEmptyEntries);

        if (words.Length < 3 || words[1] != "begin")
        {
            return false;
        }

        BgcodeThumbnailFormat format = words[0] switch
        {
            "thumbnail" => BgcodeThumbnailFormat.Png,
            "thumbnail_JPG" => BgcodeThumbnailFormat.Jpg,
            "thumbnail_QOI" => BgcodeThumbnailFormat.Qoi,
            _ => (BgcodeThumbnailFormat)(-1),
        };

        if (format < 0)
        {
            return false;
        }

        string[] size = words[2].Split('x');

        if (size.Length != 2
            || !ushort.TryParse(size[0], NumberStyles.None, CultureInfo.InvariantCulture, out ushort width)
            || !ushort.TryParse(size[1], NumberStyles.None, CultureInfo.InvariantCulture, out ushort height))
        {
            return false;
        }

        parameters = new BgcodeThumbnailParameters(format, width, height);

        return true;
    }

    private static bool IsThumbnailEnd(string line)
    {
        return line is "; thumbnail end" or "; thumbnail_JPG end" or "; thumbnail_QOI end";
    }

    /// <summary>A <c>; key = value</c> comment line's key and value, trimmed.</summary>
    private static bool TrySplitComment(string line, out string key, out string value)
    {
        key = string.Empty;
        value = string.Empty;

        if (!line.StartsWith(';'))
        {
            return false;
        }

        ReadOnlySpan<char> body = line.AsSpan(1);
        int equals = body.IndexOf('=');

        if (equals <= 0)
        {
            return false;
        }

        key = body[..equals].Trim().ToString();
        value = body[(equals + 1)..].Trim().ToString();

        return key.Length > 0;
    }

    private static string StripComment(string line)
    {
        ReadOnlySpan<char> body = line.AsSpan().TrimStart();

        if (body.Length > 0 && body[0] == ';')
        {
            body = body[1..];

            if (body.Length > 0 && body[0] == ' ')
            {
                body = body[1..];
            }
        }

        return body.ToString();
    }

    private enum Section
    {
        None,
        Thumbnail,
        Config,
        JsonConfig,
    }

    private sealed class AsciiParse
    {
        public string? Producer { get; set; }

        public string? ProducedOn { get; set; }

        public Dictionary<string, string> Captured { get; } = new(StringComparer.Ordinal);

        public List<(BgcodeThumbnailParameters parameters, byte[] image)> Thumbnails { get; } = [];

        public StringBuilder SlicerIni { get; } = new();

        public StringBuilder? SlicerJson { get; set; }

        public StringBuilder GCode { get; } = new();
    }
}
