<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" Version="9.3.0" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\libbgcode.NET\libbgcode.NET.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\libbgcode.NET.UnitTest\metadata-coreone-hf04-pla.bgcode" Link="metadata-coreone-hf04-pla.bgcode" CopyToOutputDirectory="PreserveNewest" />
    <None Include="pybgcode_convert.py" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
