using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

using AwesomeAssertions;

using Xunit;

namespace libbgcode.NET.UnitTest;

/// <summary>
/// Whole-file conversion both ways, judged by the reader: the routing of PrusaSlicer's ASCII
/// conventions into blocks, the layout written back, and the stability of the round trip.
/// </summary>
/// <remarks>
/// The ASCII fixture is Prusa's own conversion of the binary fixture, so the two are the same
/// file in both forms - which is what lets the routing be asserted against what a real slicer
/// file carries rather than against a hand-written layout.
/// </remarks>
public class BgcodeConverterTests
{
    /// <summary>A real ASCII file lands in the container with every part where the format wants it.</summary>
    [Fact]
    public void ConvertsARealAsciiFileToBinary()
    {
        byte[] binary = ToBinary(File.ReadAllText(FixturePath("ascii-coreone-hf04-pla.gcode")));

        using MemoryStream stream = new(binary, writable: false);

        BgcodeReader reader = BgcodeReader.Open(stream, new BgcodeReaderOptions { VerifyChecksum = true })!;
        List<BgcodeBlock> blocks = ReadAll(reader);
        Dictionary<BgcodeBlockType, string> texts = blocks.Where(block => block.Type != BgcodeBlockType.GCode)
                                                          .ToDictionary(block => block.Type, block => reader.ReadText(block)!);

        reader.AtEnd.Should().BeTrue();
        blocks.Select(block => block.Type).Take(4).Should().Equal(
            BgcodeBlockType.FileMetadata, BgcodeBlockType.PrinterMetadata, BgcodeBlockType.PrintMetadata, BgcodeBlockType.SlicerMetadata);
        blocks.Last().Type.Should().Be(BgcodeBlockType.GCode);

        texts[BgcodeBlockType.FileMetadata].Should().Be("Producer=PrusaSlicer 2.9.6\nProduced on=2026-08-19 at 15:00:46 UTC\n");
        texts[BgcodeBlockType.PrinterMetadata].Split('\n', StringSplitOptions.RemoveEmptyEntries)
            .Select(line => line[..line.IndexOf('=')])
            .Should().Equal(AsciiMetadataKeys.Printer, "every printer key is present, in block order");
        texts[BgcodeBlockType.PrinterMetadata].Should().StartWith("printer_model=COREONE\n");
        texts[BgcodeBlockType.PrintMetadata].Split('\n', StringSplitOptions.RemoveEmptyEntries)
            .Select(line => line[..line.IndexOf('=')])
            .Should().Equal(AsciiMetadataKeys.Print);
        texts[BgcodeBlockType.SlicerMetadata].Should().StartWith("arc_fitting=emit_center\n");
        texts[BgcodeBlockType.SlicerMetadata].Should().Contain("\nz_offset=0\n");

        string gcode = string.Concat(blocks.Where(block => block.Type == BgcodeBlockType.GCode).Select(block => reader.ReadText(block)));

        gcode.Should().StartWith("M73 P0 R0\n");
        gcode.Should().NotContain("prusaslicer_config");
        gcode.Should().NotContain("generated by");
        gcode.Should().NotContain("; filament used");
        gcode.Should().NotContain("; max_layer_z", "a gathered key leaves the G-code wherever it appeared - the slicer writes this one twice");
        gcode.Should().Contain("M73 P100 R0\n");
        gcode.Should().Contain(";LAYER_CHANGE\n", "comments that are not key = value pairs stay in the G-code");
    }

    /// <summary>
    /// The routing rules observed on the reference: gathered keys are taken from anywhere, the
    /// first occurrence wins, their lines leave the G-code, the config section goes to slicer
    /// metadata wholesale, and unknown comments stay put.
    /// </summary>
    [Fact]
    public void RoutesMetadataCommentsByKey()
    {
        const string ascii = "; generated by TestSlicer 1.0 on today\n"
                             + "; brim_width = 7\n"
                             + "; filament used [mm] = 1\n"
                             + "; probe = 1\n"
                             + "M73 P0 R0\n"
                             + "; brim_width = 9\n"
                             + "; filament used [mm] = 2\n"
                             + "G1 X1\n"
                             + "; prusaslicer_config = begin\n"
                             + "; brim_width = 0\n"
                             + "; probe_config = cfg\n"
                             + "; prusaslicer_config = end\n";

        (Dictionary<BgcodeBlockType, string> texts, string gcode) = Convert(ascii);

        texts[BgcodeBlockType.FileMetadata].Should().Be("Producer=TestSlicer 1.0\nProduced on=today\n");
        texts[BgcodeBlockType.PrinterMetadata].Should().Be("brim_width=7\nfilament used [mm]=1\n", "first occurrence wins, in list order");
        texts[BgcodeBlockType.PrintMetadata].Should().Be("filament used [mm]=1\n", "a key in both lists lands in both blocks");
        texts[BgcodeBlockType.SlicerMetadata].Should().Be("brim_width=0\nprobe_config=cfg\n");
        gcode.Should().Be("; probe = 1\nM73 P0 R0\nG1 X1\n", "gathered lines leave the G-code, unknown comments stay");
    }

    /// <summary>Thumbnail sections become thumbnail blocks, the tag naming the format.</summary>
    [Theory]
    [InlineData("thumbnail", BgcodeThumbnailFormat.Png)]
    [InlineData("thumbnail_JPG", BgcodeThumbnailFormat.Jpg)]
    [InlineData("thumbnail_QOI", BgcodeThumbnailFormat.Qoi)]
    public void ConvertsThumbnailSections(string tag, BgcodeThumbnailFormat format)
    {
        byte[] image = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17];
        string encoded = System.Convert.ToBase64String(image);
        string ascii = "; printer_model = MK4S\n"
                       + $"; {tag} begin 16x8 {encoded.Length}\n"
                       + $"; {encoded[..10]}\n"
                       + $"; {encoded[10..]}\n"
                       + $"; {tag} end\n"
                       + "G28\n";

        byte[] binary = ToBinary(ascii);

        using MemoryStream stream = new(binary, writable: false);

        BgcodeReader reader = BgcodeReader.Open(stream)!;
        BgcodeBlock thumbnail = ReadAll(reader).Single(block => block.Type == BgcodeBlockType.Thumbnail);

        thumbnail.Thumbnail.Should().Be(new BgcodeThumbnailParameters(format, 16, 8));
        reader.ReadData(thumbnail).Should().Equal(image);
    }

    /// <summary>PrusaSlicer 3's JSON section becomes the second slicer metadata block.</summary>
    [Fact]
    public void ConvertsTheJsonConfigSection()
    {
        const string ascii = "G28\n"
                             + "; prusaslicer_json_config = begin\n"
                             + "; {\"layer_height\":0.2,\n"
                             + "; \"fill\":\"15%\"}\n"
                             + "; prusaslicer_json_config = end\n"
                             + "; prusaslicer_config = begin\n"
                             + "; layer_height = 0.2\n"
                             + "; prusaslicer_config = end\n";

        byte[] binary = ToBinary(ascii);

        using MemoryStream stream = new(binary, writable: false);

        BgcodeReader reader = BgcodeReader.Open(stream)!;
        List<BgcodeBlock> slicer = ReadAll(reader).Where(block => block.Type == BgcodeBlockType.SlicerMetadata).ToList();

        slicer.Select(block => block.MetadataEncoding).Should().Equal(BgcodeMetadataEncoding.Ini, BgcodeMetadataEncoding.Json);
        reader.ReadText(slicer[0]).Should().Be("layer_height=0.2\n");
        reader.ReadText(slicer[1]).Should().Be("{\"layer_height\":0.2,\n\"fill\":\"15%\"}\n");
    }

    /// <summary>
    /// Plain G-code with none of the conventions still converts: the mandatory blocks are written
    /// empty, so the file is a container the reference reader accepts.
    /// </summary>
    [Fact]
    public void ConvertsBareGCode()
    {
        (Dictionary<BgcodeBlockType, string> texts, string gcode) = Convert("G28\nG1 X1 Y2\n");

        texts.Should().NotContainKey(BgcodeBlockType.FileMetadata, "there was no producer line");
        texts[BgcodeBlockType.PrinterMetadata].Should().BeEmpty();
        texts[BgcodeBlockType.PrintMetadata].Should().BeEmpty();
        texts[BgcodeBlockType.SlicerMetadata].Should().BeEmpty();
        gcode.Should().Be("G28\nG1 X1 Y2\n");
    }

    /// <summary>The options reach the blocks.</summary>
    [Fact]
    public void HonoursTheOptions()
    {
        BgcodeConverterOptions options = new()
        {
            ChecksumType = BgcodeChecksumType.None,
            GCodeEncoding = BgcodeGCodeEncoding.None,
            GCodeCompression = BgcodeCompression.None,
            SlicerMetadataCompression = BgcodeCompression.Heatshrink11,
        };

        byte[] binary = ToBinary("G28\n; prusaslicer_config = begin\n; a = 1\n; prusaslicer_config = end\n", options);

        using MemoryStream stream = new(binary, writable: false);

        BgcodeReader reader = BgcodeReader.Open(stream)!;
        List<BgcodeBlock> blocks = ReadAll(reader);

        reader.FileHeader.ChecksumType.Should().Be(BgcodeChecksumType.None);
        blocks.Single(block => block.Type == BgcodeBlockType.SlicerMetadata).Compression.Should().Be(BgcodeCompression.Heatshrink11);
        blocks.Single(block => block.Type == BgcodeBlockType.GCode).GCodeEncoding.Should().Be(BgcodeGCodeEncoding.None);
        blocks.Single(block => block.Type == BgcodeBlockType.GCode).Compression.Should().Be(BgcodeCompression.None);
    }

    /// <summary>The ASCII written back has PrusaSlicer's layout: producer line, head comments, G-code, print statistics, config.</summary>
    [Fact]
    public void WritesAsciiInTheSlicersLayout()
    {
        string ascii = ToAscii(File.ReadAllBytes(FixturePath("metadata-coreone-hf04-pla.bgcode")));
        string[] lines = ascii.Split('\n');

        lines[0].Should().Be("; generated by PrusaSlicer 2.9.6 on 2026-08-19 at 15:00:46 UTC");
        lines[1].Should().BeEmpty();
        lines[2].Should().BeEmpty();
        lines[3].Should().Be("; printer_model = COREONE");
        ascii.Should().Contain("\n; objects_info = {");
        ascii.IndexOf("; estimated first layer printing time (normal mode) = 14s", StringComparison.Ordinal)
             .Should().BeGreaterThan(ascii.IndexOf("M73 P100 R0", StringComparison.Ordinal), "print statistics follow the G-code");
        ascii.Should().Contain("\n; prusaslicer_config = begin\n; arc_fitting = emit_center\n");
        ascii.Should().EndWith("; z_offset = 0\n; prusaslicer_config = end\n");
    }

    /// <summary>Thumbnails and the JSON block are written back in the forms the slicer's files use.</summary>
    [Fact]
    public void WritesThumbnailAndJsonSections()
    {
        byte[] image = [0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF];
        byte[] binary;

        using (MemoryStream stream = new())
        {
            using (BgcodeWriter writer = new(stream, leaveOpen: true))
            {
                writer.WritePrinterMetadata("printer_model=MK4S\n");
                writer.WriteThumbnail(new BgcodeThumbnailParameters(BgcodeThumbnailFormat.Qoi, 1, 1), image);
                writer.WritePrintMetadata("filament cost=0.00\n");
                writer.WriteSlicerMetadata("layer_height=0.2\n");
                writer.WriteSlicerMetadata("{\"layer_height\":0.2}", BgcodeMetadataEncoding.Json);
                writer.WriteGCode("G28\n");
            }

            binary = stream.ToArray();
        }

        string ascii = ToAscii(binary);

        ascii.Should().Contain("; printer_model = MK4S\n\n;\n; thumbnail_QOI begin 1x1 8\n; qrvM3e7/\n; thumbnail_QOI end\n;\n\nG28\n");
        ascii.Should().Contain("\n; filament cost = 0.00\n\n; prusaslicer_json_config = begin\n; {\"layer_height\":0.2}\n; prusaslicer_json_config = end\n\n; prusaslicer_config = begin\n; layer_height = 0.2\n; prusaslicer_config = end\n");
    }

    /// <summary>
    /// Converting back and forth reaches a fixed point after one round: the second ASCII equals
    /// the first, and the second container's metadata equals the first's.
    /// </summary>
    [Fact]
    public void RoundTripIsStable()
    {
        byte[] first = ToBinary(File.ReadAllText(FixturePath("ascii-coreone-hf04-pla.gcode")));
        string firstAscii = ToAscii(first);
        byte[] second = ToBinary(firstAscii);
        string secondAscii = ToAscii(second);

        secondAscii.Should().Be(firstAscii);
        MetadataOf(second).Should().Equal(MetadataOf(first));
    }

    /// <summary>What is not a container, or a broken one, is refused with a reason rather than a null.</summary>
    [Fact]
    public void RefusesWhatItCannotConvert()
    {
        byte[] whole = File.ReadAllBytes(FixturePath("metadata-coreone-hf04-pla.bgcode"));

        Action notBgcode = () => ToAscii(Encoding.ASCII.GetBytes("G28\n"));
        Action truncated = () => ToAscii(whole[..200]);

        notBgcode.Should().Throw<InvalidDataException>().WithMessage("*header*");
        truncated.Should().Throw<InvalidDataException>();
    }

    private static byte[] ToBinary(string ascii, BgcodeConverterOptions? options = null)
    {
        using StringReader reader = new(ascii);
        using MemoryStream binary = new();

        BgcodeConverter.ToBinary(reader, binary, options);

        return binary.ToArray();
    }

    private static string ToAscii(byte[] binary)
    {
        using MemoryStream stream = new(binary, writable: false);
        using StringWriter writer = new();

        BgcodeConverter.ToAscii(stream, writer);

        return writer.ToString();
    }

    private static (Dictionary<BgcodeBlockType, string> texts, string gcode) Convert(string ascii)
    {
        using MemoryStream stream = new(ToBinary(ascii), writable: false);

        BgcodeReader reader = BgcodeReader.Open(stream, new BgcodeReaderOptions { VerifyChecksum = true })!;
        List<BgcodeBlock> blocks = ReadAll(reader);

        reader.AtEnd.Should().BeTrue();

        Dictionary<BgcodeBlockType, string> texts = blocks.Where(block => block.Type is not (BgcodeBlockType.GCode or BgcodeBlockType.Thumbnail))
                                                          .ToDictionary(block => block.Type, block => reader.ReadText(block)!);
        string gcode = string.Concat(blocks.Where(block => block.Type == BgcodeBlockType.GCode).Select(block => reader.ReadText(block)));

        return (texts, gcode);
    }

    private static List<string> MetadataOf(byte[] binary)
    {
        using MemoryStream stream = new(binary, writable: false);

        BgcodeReader reader = BgcodeReader.Open(stream)!;

        return ReadAll(reader).Where(block => block.Type != BgcodeBlockType.GCode).Select(block => reader.ReadText(block) ?? "<binary>").ToList();
    }

    private static List<BgcodeBlock> ReadAll(BgcodeReader reader)
    {
        List<BgcodeBlock> blocks = [];

        while (reader.NextBlock() is { } block)
        {
            blocks.Add(block);
        }

        return blocks;
    }

    private static string FixturePath(string name)
    {
        return Path.Combine(AppContext.BaseDirectory, name);
    }
}
