<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>gcode2bin</AssemblyName>
    <RootNamespace>libbgcode.NET.Tools</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\libbgcode.NET\libbgcode.NET.csproj" />
  </ItemGroup>

</Project>
